#!/bin/sh

export WWC_PORT=6101

cd Docker

docker-compose down --volumes
rm -rf htdocs/
rm -rf fcgi-bin/
rm -rf data/

mkdir htdocs
cp -a ../htdocs/. htdocs/
mkdir fcgi-bin
cp ../WorldWideCalendar fcgi-bin/
mkdir data
cp -a ../data/. data/

docker build -t worldwidecalendar -f WWC_Dockerfile .
docker build -t astrodata -f Data_Dockerfile .
docker-compose up -d